version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "7000:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data+
      - ./db_scripts:/docker-entrypoint-initdb.d/
    networks:
      - network

networks:
  network:
    driver: bridge